In [1]:
import numpy as np

In [2]:
a = np.array([0,0,0,0,0,0,0,0,0,0])
print(a)

b = np.array([5,5,5,5,5,5,5,5,5,5])
print(b)

[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


In [3]:
c = np.random.random((3,3,3))
print(c)

[[[0.84151291 0.57357358 0.06196957]
  [0.58569768 0.11983734 0.90512788]
  [0.77238496 0.78917457 0.38815648]]

 [[0.24019949 0.65519549 0.50233063]
  [0.84531647 0.49032737 0.27298913]
  [0.21446758 0.13396266 0.09180864]]

 [[0.19784998 0.81576302 0.65657779]
  [0.37268734 0.32576534 0.14950219]
  [0.06867916 0.84293048 0.29243211]]]


In [6]:
%memit d = np.array([1,7,13,105,208]) 

In [7]:
print(d)

[  1   7  13 105 208]


In [8]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [9]:
e = np.arange(10,22).reshape((3,4))
print(e)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [10]:
f = np.zeros((4, 4))
f[::2, 1::2] = 1
f[1::2, ::2] = 1
print(f)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [11]:
original_array = np.array([10, 20, 30])

first_array_to_append = np.array([40, 50, 60])
second_array_to_append = np.array([70, 80, 90])

np.concatenate([original_array, first_array_to_append, second_array_to_append])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
random_array = np.random.randint(100, size = 1000)
#print(random_array)
print("Average = ", np.average(random_array))
print("Variance = ", np.var(random_array))
print("Standard Deviation = ", np.std(random_array))

Average =  49.457
Variance =  854.9101509999999
Standard Deviation =  29.2388466085788


In [13]:
print("sine = ", np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosie = ", np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent = ", np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine =  [0.         0.5        0.70710678 0.8660254  1.        ]
cosie =  [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent =  [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [14]:
array = np.array([3, 6, 9, 25, 10, 8])
print(array)

array_a = array[1::]
print(array_a)

[ 3  6  9 25 10  8]
[ 6  9 25 10  8]


In [15]:
array_b = array[:5:]
print(array_b)

[ 3  6  9 25 10]


In [17]:
array_c = array[::2]
print(array_c)

[ 3  9 10]


In [18]:
array_d = array[1::2]
print(array_d)

[ 6 25  8]


In [19]:
array_e = array[::-1]
print(array_e)

[ 8 10 25  9  6  3]


In [20]:
multi_dim_array = np.arange(0,32).reshape((8,4))
print(multi_dim_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [21]:
multi_dim_array[0,2] = 0

print(multi_dim_array)

[[ 0  1  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [22]:
print(multi_dim_array[:,1])

[ 1  5  9 13 17 21 25 29]


In [23]:
print(multi_dim_array[0:3,0:3])

[[ 0  1  0]
 [ 4  5  6]
 [ 8  9 10]]


In [25]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])


In [26]:
a = a.reshape(4,1)

In [27]:
a

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [28]:
a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [29]:
(a+b).shape

(4, 3)

In [30]:
x = np.arange(4)
y = np.ones(5)

In [31]:
x.shape

(4,)

In [32]:
x.shape

(4,)

In [33]:
y.shape

(5,)

In [34]:
x_new = x[:, np.newaxis]

In [35]:
x_new + y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [36]:
(x_new+y).shape

(4, 5)

2.1 by using numpy broadcasting (10 points) 

In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([1, 2, 3, 4, 5, 6])
print("a = ", a)
print("b = ", b)

a =  [1 2 3 4 5 6]
b =  [1 2 3 4 5 6]


In [38]:
a_new = a[:, np.newaxis] 
print("a_new = \n", a_new)

a_new = 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [39]:
a_new * b

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

2.2 by using Python nested for-loop (10 points).

In [40]:
m = np.array([1, 2, 3, 4, 5, 6])
n = np.array([1, 2, 3, 4, 5, 6])
print("m = ", m)
print("n = ", n)

m =  [1 2 3 4 5 6]
n =  [1 2 3 4 5 6]


In [41]:
result = np.zeros(36).reshape((6, 6))

In [42]:
for i in m:
    for j in n:
        result[i-1, j-1] = i*j

print("result = \n", result)

result = 
 [[ 1.  2.  3.  4.  5.  6.]
 [ 2.  4.  6.  8. 10. 12.]
 [ 3.  6.  9. 12. 15. 18.]
 [ 4.  8. 12. 16. 20. 24.]
 [ 5. 10. 15. 20. 25. 30.]
 [ 6. 12. 18. 24. 30. 36.]]
